"""Module knowledge generation and feature update command."""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path

import yaml

from hilog_agent.config import Config
from hilog_agent.diff_safety import validate_diff
from hilog_agent.models.feature import FeatureModuleIndex, FeatureYaml
from hilog_agent.models.module import ModuleMetadata, ModuleYaml
from hilog_agent.models.result import (
    AddModuleResult,
    WrittenFile,
)
from hilog_agent.store import FeatureStore


def add_module(
    *,
    feature: str,
    module: str,
    code_path: str,
    store: FeatureStore,
    config: Config,
    force: bool = False,
    backup: bool = False,
    dry_run: bool = False,
    review: bool = False,
) -> AddModuleResult:
    """Generate module knowledge and update feature YAML.

    dry_run: execute full flow but don't write to disk.
    review: write files with review markers.
    """
    warnings: list[str] = []
    written: list[WrittenFile] = []

    # 1. Validate paths
    features_dir = Path(config.features_dir)
    feat_dir = features_dir / feature
    mod_out = feat_dir / "modules" / f"{module}.yaml"

    if not feat_dir.exists():
        raise ValueError(f"Feature directory '{feature}' not found under {features_dir}")

    # 2. Read and validate current feature.yaml
    current_feature = store.read_feature(feature)

    # 3. Check if module already exists
    if mod_out.exists() and not force:
        raise ValueError(
            f"Module '{module}' already exists in feature '{feature}'. Use --force to overwrite."
        )

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    generated_by = "hilog-agent"
    if review:
        generated_by = "hilog-agent [pending-review]"

    mod_metadata = ModuleMetadata(
        generated_by=generated_by,
        generated_at=now,
        review_notes=["Generated by add-module — review required."] if review else [],
    )
    module_yaml = ModuleYaml(
        name=module,
        display_name=module,
        code_path=code_path,
        responsibility="[LLM-generated placeholder]",
        symbols=[],
        logs=[],
        candidate_steps=[],
        failure_signals=[],
        metadata=mod_metadata,
    )

    # Build updated feature.yaml
    new_mod_idx = FeatureModuleIndex(
        name=module,
        yaml_path=f"modules/{module}.yaml",
        responsibility="[LLM-generated placeholder]",
    )

    updated_data = current_feature.model_dump()
    updated_data["modules"].append(new_mod_idx.model_dump())
    updated_data["metadata"]["version"] = current_feature.metadata.version + 1
    updated_data["metadata"]["updated_at"] = now
    if review:
        updated_data["metadata"]["review_notes"] = list(current_feature.metadata.review_notes) + [
            f"Module '{module}' added via add-module — pending review"
        ]

    updated_feature = FeatureYaml.model_validate(updated_data)

    # Diff safety
    diff_errors = validate_diff(current_feature, updated_feature)
    if diff_errors:
        raise ValueError(f"Diff safety validation failed: {'; '.join(diff_errors)}")

    # Write (unless dry_run)
    if not dry_run:
        if backup and mod_out.exists():
            backup_path = mod_out.with_suffix(f".yaml.bak.{now.replace(' ', '_')}")
            os.rename(str(mod_out), str(backup_path))
            written.append(WrittenFile(path=str(backup_path), action="backup_created"))

        os.makedirs(str(mod_out.parent), exist_ok=True)
        with open(mod_out, "w") as f:
            yaml.dump(module_yaml.model_dump(exclude_none=True), f, allow_unicode=True)
        written.append(WrittenFile(path=str(mod_out), action="created"))

        feat_yaml_path = feat_dir / "feature.yaml"
        if backup:
            bak = feat_yaml_path.with_suffix(f".yaml.bak.{now.replace(' ', '_')}")
            os.rename(str(feat_yaml_path), str(bak))
            written.append(WrittenFile(path=str(bak), action="backup_created"))
        with open(feat_yaml_path, "w") as f:
            yaml.dump(updated_feature.model_dump(exclude_none=True), f, allow_unicode=True)
        written.append(WrittenFile(path=str(feat_yaml_path), action="updated"))

    return AddModuleResult(
        feature=feature,
        module=module,
        written_files=written,
        analysis_summary=[f"Generated module YAML for {module}"],
        change_summary=[
            f"Appended module index for {module}, version → {updated_feature.metadata.version}"
        ],
        warnings=warnings,
        related_feature_suggestions=[],
    )
